const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = __dirname;
const dir = path.join(root, '신청내역');
fs.mkdirSync(dir, {recursive:true});
const jsonFile = path.join(dir, 'applications.json');
const excelFile = path.join(dir, '겜마루_신청내역.xlsx');
const adminToken=crypto.randomBytes(24).toString('hex');
const fields = [['접수번호','id'],['접수일시','submittedAt'],['이름','name'],['이메일','email'],['전화번호','tel'],['나이','age'],['생년월일','birth'],['성별','gender'],['거주 지역','city'],['관심 분야','interest'],['역량','ability'],['관심 있는 게임','games'],['게임 개발 장르','genre'],['지원 사유','reason']];
let records = fs.existsSync(jsonFile) ? JSON.parse(fs.readFileSync(jsonFile,'utf8')) : [];
function xml(v){return String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));}
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
const crcTable = Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(b){let n=0xffffffff;for(const v of b)n=crcTable[(n^v)&255]^(n>>>8);return (n^0xffffffff)>>>0;}
function zip(files){const entries=[],central=[];let offset=0;for(const [name,body] of Object.entries(files)){const n=Buffer.from(name),b=Buffer.from(body),c=crc(b);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt32LE(c,14);h.writeUInt32LE(b.length,18);h.writeUInt32LE(b.length,22);h.writeUInt16LE(n.length,26);entries.push(h,n,b);const d=Buffer.alloc(46);d.writeUInt32LE(0x02014b50);d.writeUInt16LE(20,4);d.writeUInt16LE(20,6);d.writeUInt16LE(0x800,8);d.writeUInt32LE(c,16);d.writeUInt32LE(b.length,20);d.writeUInt32LE(b.length,24);d.writeUInt16LE(n.length,28);d.writeUInt32LE(offset,42);central.push(d,n);offset+=h.length+n.length+b.length;}const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...entries,cd,end]);}
function workbook(rows){const data=[fields.map(f=>f[0]),...rows.map(r=>fields.map(([,key])=>r[key]??''))];const sheet=data.map((r,i)=>`<row r="${i+1}"${i===0?' ht="30" customHeight="1"':''}>${r.map((v,j)=>{const cell=col(j)+(i+1);if(i>0&&j===5&&v!=='')return `<c r="${cell}" s="1"><v>${Number(v)}</v></c>`;return `<c r="${cell}" t="inlineStr" s="${i===0?2:1}"><is><t xml:space="preserve">${xml(Array.isArray(v)?v.join(', '):v)}</t></is></c>`;}).join('')}</row>`).join('');return zip({
'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
'_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
'xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="신청내역" sheetId="1" r:id="rId1"/></sheets></workbook>',
'xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
'xl/styles.xml':'<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Malgun Gothic"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Malgun Gothic"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF202838"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>',
'xl/worksheets/sheet1.xml':`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:N${data.length}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="2" width="27" customWidth="1"/><col min="3" max="3" width="16" customWidth="1"/><col min="4" max="5" width="27" customWidth="1"/><col min="6" max="6" width="10" customWidth="1"/><col min="7" max="9" width="18" customWidth="1"/><col min="10" max="13" width="30" customWidth="1"/><col min="14" max="14" width="65" customWidth="1"/></cols><sheetData>${sheet}</sheetData><autoFilter ref="A1:N${data.length}"/></worksheet>`});}
function atomic(file,body){const tmp=file+'.tmp';fs.writeFileSync(tmp,body);fs.renameSync(tmp,file);}
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function normalize(data){const r={};for(const [,key] of fields.slice(2)){const v=data[key]??'';if(key==='interest'){if(!Array.isArray(v)||v.some(x=>!['프로그래밍','디자인','사운드','기획'].includes(x)))throw Error('관심 분야를 확인해주세요.');r[key]=v;}else{if(typeof v!=='string'||v.length>(key==='reason'?2000:300))throw Error('입력 내용을 확인해주세요.');r[key]=v.trim();}}for(const key of ['name','email','tel','games','genre','reason'])if(!r[key])throw Error('필수 항목을 모두 작성해주세요.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email))throw Error('이메일 형식을 확인해주세요.');if(r.age&&(!/^\d+$/.test(r.age)||+r.age<1||+r.age>120))throw Error('나이는 1~120으로 입력해주세요.');return r;}
function start(){atomic(excelFile,workbook(records));const port=Number(process.env.PORT||8766);const server=http.createServer(async(req,res)=>{
try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(fs.readFileSync(path.join(root,'gammaru-application.html')));return;}
if(req.method==='POST'&&url.pathname==='/api/applications'){const origin=req.headers.origin;if(origin&&origin!==`http://${req.headers.host}`){send(res,403,{error:'허용되지 않은 요청입니다.'});return;}let bytes=0,parts=[];for await(const b of req){bytes+=b.length;if(bytes>20000){send(res,413,{error:'입력 내용이 너무 큽니다.'});return;}parts.push(b);}let data;try{data=JSON.parse(Buffer.concat(parts).toString('utf8'));}catch{send(res,400,{error:'요청 형식을 확인해주세요.'});return;}let record;try{record=normalize(data);}catch(e){send(res,400,{error:e.message});return;}if(typeof data.requestId!=='string'||!/^[a-f0-9-]{36}$/i.test(data.requestId)){send(res,400,{error:'신청서를 새로 열어 다시 시도해주세요.'});return;}const prior=records.find(r=>r.requestId===data.requestId);if(prior){send(res,200,{id:prior.id});return;}const next=[...records,{...record,id:crypto.randomUUID(),requestId:data.requestId,submittedAt:new Date().toLocaleString('sv-SE',{timeZone:'Asia/Seoul'})}];try{const bytes=workbook(next);atomic(jsonFile,JSON.stringify(next,null,2));try{atomic(excelFile,bytes);}catch(error){atomic(jsonFile,JSON.stringify(records,null,2));throw error;}records=next;}catch(e){console.error(e.message);send(res,503,{error:'저장하지 못했습니다. 신청내역 엑셀 파일이 열려 있다면 닫고 다시 제출해주세요.'});return;}send(res,201,{id:next.at(-1).id});return;}
if(req.method==='GET'&&(url.pathname==='/admin'||url.pathname==='/admin/export')){if(url.searchParams.get('token')!==adminToken){send(res,403,{error:'실행 창에 표시된 운영자 주소를 사용해주세요.'});return;}if(url.pathname==='/admin/export'){res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent('겜마루_신청내역.xlsx'),'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});res.end(workbook(records));return;}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer'});res.end(`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>겜마루 신청 관리</title><style>body{background:#0c1018;color:#f4f2ea;font:16px/1.7 sans-serif;max-width:850px;margin:60px auto;padding:24px}a{display:inline-block;background:#eb55bc;color:#101018;padding:12px 22px;text-decoration:none;font-weight:bold}table{width:100%;border-collapse:collapse;margin-top:30px}td,th{text-align:left;padding:14px;border-bottom:1px solid #303541}</style><h1>겜마루 신청 관리</h1><p>총 ${records.length}건 접수</p><p><a href="/" target="_blank" rel="noopener">신청서 열기</a></p><a href="/admin/export?token=${adminToken}">전체 신청 내역 엑셀 다운로드</a><p>최신 내역은 페이지를 새로고침하여 확인하세요. 다운로드한 엑셀은 내려받은 시점의 복사본입니다.</p><p>실시간 저장 파일: ${xml(excelFile)}</p><table><tr><th>접수일시</th><th>이름</th><th>관심 분야</th></tr>${records.map(r=>`<tr><td>${xml(r.submittedAt)}</td><td>${xml(r.name)}</td><td>${xml(r.interest.join(', '))}</td></tr>`).join('')}</table></html>`);return;}
send(res,404,{error:'페이지를 찾을 수 없습니다.'});}catch(e){console.error(e.message);if(!res.headersSent)send(res,500,{error:'저장 중 오류가 발생했습니다. 다시 시도해주세요.'});}});server.listen(port,'127.0.0.1',()=>{console.log(`신청서: http://127.0.0.1:${port}\n운영자: http://127.0.0.1:${port}/admin?token=${adminToken}\n엑셀 저장: ${excelFile}\n종료: Ctrl+C`);if(process.argv.includes('--open-admin')){require('node:child_process').spawn('explorer.exe',[`http://127.0.0.1:${port}/admin?token=${adminToken}`],{windowsHide:true}).on('error',()=>console.log('실행 창의 운영자 주소를 브라우저에서 열어주세요.'));}});server.on('error',e=>{console.error(e.code==='EADDRINUSE'?'다른 신청서 실행 창이 열려 있습니다. 기존 창을 Ctrl+C로 종료한 후 이 폴더에서 다시 실행하세요. 기존 창의 프로그램은 기존 폴더에 저장합니다.':e.message);process.exitCode=1;});}
module.exports={workbook,normalize};if(require.main===module)start();
